{% set name = "pathvalidate" %}
{% set version = "3.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5d07b1e2374187040612a1fcd2bcb2919f8db180df254c9581bb90bf903377d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - python >=3.5

test:
  imports:
    - pathvalidate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/pathvalidate
  summary: pathvalidate is a Python library to sanitize/validate a string such as filenames/file-paths/etc.
  dev_url: https://github.com/thombashi/pathvalidate
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
